# Generated by Django 4.1.5 on 2023-04-12 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Billing1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('S_no', models.CharField(max_length=50)),
                ('Items', models.CharField(choices=[('Egg Maggi', 'Egg Maggi'), ('Veg Maggi', 'Veg Maggi'), ('Fry Maggi', 'Fry Maggi'), ('Schezwal Egg Maggi', 'Schezwal Egg Maggi'), ('Schezwal Veg Maggi', 'Schezwal Veg Maggi'), ('Schezwal Fry Maggi', 'Schezwal Fry Maggi')], max_length=50)),
                ('Quantity', models.CharField(max_length=50)),
                ('PricePerPc', models.CharField(max_length=50)),
                ('Total_Price', models.CharField(max_length=50)),
            ],
        ),
    ]
