# Generated by Django 4.1.5 on 2023-04-14 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_no', models.CharField(max_length=50)),
                ('items', models.CharField(choices=[('Egg Maggi', 'Egg Maggi'), ('Veg Maggi', 'Veg Maggi'), ('Fry Maggi', 'Fry Maggi'), ('Schezwal Egg Maggi', 'Schezwal Egg Maggi'), ('Schezwal Veg Maggi', 'Schezwal Veg Maggi'), ('Schezwal Fry Maggi', 'Schezwal Fry Maggi')], max_length=50)),
                ('quantity', models.CharField(max_length=50)),
                ('price_per_pc', models.CharField(max_length=50)),
                ('total_price', models.CharField(max_length=50)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
