# Generated by Django 4.1.5 on 2023-04-14 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_billinghistory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='billinghistory',
            old_name='items',
            new_name='Items',
        ),
        migrations.RenameField(
            model_name='billinghistory',
            old_name='price_per_pc',
            new_name='PricePerPc',
        ),
        migrations.RenameField(
            model_name='billinghistory',
            old_name='quantity',
            new_name='Quantity',
        ),
        migrations.RenameField(
            model_name='billinghistory',
            old_name='s_no',
            new_name='S_no',
        ),
        migrations.RenameField(
            model_name='billinghistory',
            old_name='total_price',
            new_name='Total_Price',
        ),
        migrations.RemoveField(
            model_name='billinghistory',
            name='created_date',
        ),
    ]
