# Generated by Django 4.1.5 on 2023-03-16 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='signup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FIRST_NAME', models.CharField(choices=[('Mr', 'Mr'), ('MrS', 'MrS')], max_length=50)),
                ('MIDDLE_NAME', models.CharField(max_length=50)),
                ('LAST_NAME', models.CharField(max_length=50)),
                ('GENDER', models.CharField(choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE'), ('OTHERS', 'OTHERS')], max_length=50)),
                ('AGE', models.IntegerField()),
                ('MARITAL', models.CharField(max_length=50, null=True)),
                ('PHONE_NUMBER', models.IntegerField()),
                ('EMAIL_ID', models.EmailField(max_length=254, null=True)),
                ('USER_NAME', models.CharField(max_length=50, null=True)),
                ('PASSWORD', models.CharField(max_length=50, null=True)),
                ('RE_PASSWORD', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
