# Generated by Django 4.1.5 on 2023-03-16 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup',
            name='MARITAL',
            field=models.CharField(choices=[('single', 'single'), ('married', 'married')], max_length=50, null=True),
        ),
    ]
