# Generated by Django 4.1.5 on 2023-03-16 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_signup_marital'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup',
            name='PHONE_NUMBER',
            field=models.CharField(max_length=10),
        ),
    ]
