# Generated by Django 4.1.5 on 2023-03-17 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_login'),
    ]

    operations = [
        migrations.DeleteModel(
            name='login',
        ),
        migrations.RenameField(
            model_name='signup',
            old_name='PASSWORD',
            new_name='password',
        ),
        migrations.RenameField(
            model_name='signup',
            old_name='USER_NAME',
            new_name='usernames',
        ),
    ]
