# Generated by Django 4.1.5 on 2023-03-17 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_delete_login_rename_password_signup_password_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='signup',
            old_name='usernames',
            new_name='usernam',
        ),
    ]
