# Generated by Django 4.1.5 on 2023-03-17 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_rename_usernames_signup_usernam'),
    ]

    operations = [
        migrations.RenameField(
            model_name='signup',
            old_name='usernam',
            new_name='username',
        ),
    ]
