# Generated by Django 4.2.4 on 2024-06-13 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('myapp', '0002_delete_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('contact_number', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('purpose', models.CharField(choices=[('startup', 'Start-up'), ('personal', 'Personal')], max_length=10)),
                ('message', models.TextField()),
            ],
        ),
    ]
