# Generated by Django 4.1.5 on 2023-04-11 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_billing2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Billings1',
        ),
    ]
