# Generated by Django 4.1.5 on 2023-03-15 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='signup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FIRST_NAME', models.CharField(choices=[('Mr', 'Mr'), ('MrS', 'MrS')], max_length=50)),
                ('MIDDLE_NAME', models.CharField(max_length=50)),
                ('LAST_NAME', models.CharField(max_length=50)),
                ('GENDER', models.CharField(choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE'), ('OTHERS', 'OTHERS')], max_length=50)),
                ('AGE', models.IntegerField(max_length=3)),
                ('PHONE_NUMBER', models.IntegerField(max_length=15)),
            ],
        ),
    ]
