# Generated by Django 4.1.5 on 2023-03-15 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup',
            name='AGE',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='signup',
            name='PHONE_NUMBER',
            field=models.IntegerField(),
        ),
    ]
