# Generated by Django 4.1.5 on 2023-03-16 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_signup_email_id_signup_password_signup_re_password_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup',
            name='MARITAL',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
