# Generated by Django 4.1.5 on 2023-03-16 00:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_signup_marital'),
    ]

    operations = [
        migrations.DeleteModel(
            name='signup',
        ),
    ]
